### ISSUE TITLE
[weeklog] 3~4주차 태스크

### ISSUE THREAD

**Issue by plas318** [purgo-capstone/back#4]
### Hospital 
- [x] Model 개발
- [x] Serializer 개발
- [x] API 개발

### User
- [x] Model 개발
- [x] Serializer 개발
- [x] API 개발

### Doctor
- [x] #5
- [x] Serializer 개발
- [x] API 개발

### SalesHistory
- [x] Model 개발
- [x] Serializer 개발
- [x] API 개발

### HospitalProduct
- [ ] Model 개발
- [ ] Serializer 개발
- [ ] API 개발

### Product
- [ ] Model 개발
- [ ] Serializer 개발
- [ ] API 개발

**Comment by jaehyeonpy** [comment]
지금 진행되고 있는 task, subtask와는 체계가 달라 close 합니다.
